//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ball.Config {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class CashShopTemplate : IGeneratorObject {
    
    // 索引
    [ProtoMember(1)]
    public int Id;
    
    // 类型
    [ProtoMember(2)]
    public int Type;
    
    // 排序
    [ProtoMember(3)]
    public int Sort;
    
    // 渠道
    [ProtoMember(4)]
    public int[] Channels;
    
    // 商品编号
    [ProtoMember(5)]
    public string PayId;
    
    // 价格
    [ProtoMember(6)]
    public double Price;
    
    // 钻石
    [ProtoMember(7)]
    public int Diamond;
    
    // 钻石数
    [ProtoMember(8)]
    public int Amount;
    
    // 赠送钻石数
    [ProtoMember(9)]
    public int FreeAmount;
    
    // 首购赠送钻石数
    [ProtoMember(10)]
    public int FirstFreeAmount;
    
    // 图标
    [ProtoMember(11)]
    public string Icon;
    
    public virtual void OnInit() {
    }
    
    public static CashShopTemplate[] Load() {
      return Load<CashShopTemplate>();
    }
    
    public static T[] Load<T>()
      where T : CashShopTemplate, new () {
      return GeneratorUtility.Load<T>("CashShopsConfig", "CashShop");
    }
  }
}
