//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ball.Config
{
    using ProtoBuf;

    [ProtoContract()]
    public class SkillTemplate : IGeneratorObject
    {
        // 索引
        [ProtoMember(1)]
        public int Id;

        // 名称
        [ProtoMember(2)]
        public string Name;

        // 描述
        [ProtoMember(3)]
        public string Description;

        // 基础等级
        [ProtoMember(4)]
        public int Level;

        // 基础亲密度
        [ProtoMember(5)]
        public int Influence;

        // 阵营
        [ProtoMember(6)]
        public int Camp;

        // 属性
        [ProtoMember(7)]
        public int[] Propertiess;

        // 技能卡类型
        [ProtoMember(8)]
        public int Position;

        // 技能类名
        [ProtoMember(9)]
        public string SkillClassName;

        // 编号
        [ProtoMember(10)]
        public string Code;

        public virtual void OnInit()
        {
        }

        public static SkillTemplate[] Load()
        {
            return Load<SkillTemplate>();
        }

        public static T[] Load<T>()
          where T : SkillTemplate, new()
        {
            return GeneratorUtility.Load<T>("SkillsConfig", "Skill");
        }
    }
}
